# -*- coding: utf-8 -*-
"""LabelGen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1js8YIHObDfgVT7Hr3dKcIrWDUyK3nBPe
"""
import sys
import pandas as pd
import json

def wce(r):
    try:
        if r>=1.5 & r<=2:
            return 1
        else: 
            return 0
    except:
        return 'Nan'          
       
"================================================"
def de(r):
    try:
        if r>=0.5 & r<=1.5:
            return 1
        else: 
            return 0 
    except:
        return 'Nan'        
"================================================"
def eps(r):
    try:
        if r>=1 & r<=99:
            return 1
        else: 
            return 0 
    except:
        return "Nan"
"================================================"
def pe(r):
    try:        
        if r>13:
            return 1
        else: 
            return 0
    except:
        return 'Nan'
"================================================"
def roe(r):
    try:
        if r>15:
            return 1
        else: 
            return 0
    except:
        return 'Nan'
"================================================"
def ro40(r):
    try: 
        if r>40:
            return 1
        else: 
            return 0
    except:
        return 'Nan'    
"================================================"
def market_cap(r):
    try: 
        if r>2000000000:
            return 1
        else: 
            return 0
    except:
        return 'Nan'       
"================================================"
def growth_rate(r):
    try:
        if r>60:
            return 1
        else: 
            return 0
    except:
        return 'Nan'        
"================================================"
def profit_margin(r):
    try:
        if r>20:
            return 1
        else: 
            return 0
    except:
        return 'Nan'        
"================================================"
def gross_margin(r):
    try:
        if r>0.5:
            return 1
        else: 
            return 0
    except:
        return 'Nan'        
"================================================"
def magic_num(r):
    try:    
        if r>1:
            return 1
        else: 
            return 0
    except:
        return 'Nan'        
"================================================"
def chun_rate(r):
  try:
    if r<1:
      return 1
    else: 
      return 0
  except:
    return 'Nan' 

"=============================================="